version: '3.8'

services:
  api-muve-player-pg:
    image: bitnami/postgresql
    container_name: api-muve-player-pg
    ports:
      - 5434:5434
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=apimuveplayer
    networks:
      - observability

networks:
  observability:
    external: true
