version: '3.8'

services:
  api-muve-player-pg:
    image: bitnami/postgresql
    container_name: api-muve-player-pg
    ports:
      - "25060:5432" # Porta externa:interna (5432 é a porta padrão do PostgreSQL dentro do contêiner)
    environment:
      - POSTGRESQL_USERNAME=doadmin
      - POSTGRESQL_PASSWORD=AVNS_HlgD2F1L5xeojoXowXU
      - POSTGRESQL_DATABASE=defaultdb
      - POSTGRESQL_PORT_NUMBER=25060
      - POSTGRESQL_HOST=muve-db-do-user-17463865-0.j.db.ondigitalocean.com
    networks:
      - observability

networks:
  observability:
    external: true
